import { Manga, Chapter, Review, UserProfile } from './types'

function generateChapters(count: number): Chapter[] {
    const chapters: Chapter[] = []
    for (let i = count; i >= 1; i--) {
        const daysAgo = (count - i) * 3
        const date = new Date()
        date.setDate(date.getDate() - daysAgo)
        chapters.push({
            id: `ch-${i}`,
            number: i,
            title: i === count ? 'The Beginning of the End' : i === 1 ? 'Prologue' : `Chapter ${i}`,
            pages: Math.floor(Math.random() * 25) + 15,
            releasedAt: date.toISOString(),
            isRead: i < count * 0.6,
        })
    }
    return chapters
}

export const mockManga: Manga[] = [
    {
        id: '1',
        title: 'Solo Leveling',
        altTitles: ['나 혼자만 레벨업', 'I Level Up Alone'],
        slug: 'solo-leveling',
        cover: 'https://placehold.co/300x450/1a1a2e/7c3aed?text=Solo+Leveling&font=montserrat',
        banner: 'https://placehold.co/1200x400/1a1a2e/7c3aed?text=Solo+Leveling+Banner&font=montserrat',
        type: 'manhwa',
        status: 'completed',
        author: 'Chugong',
        artist: 'DUBU (REDICE Studio)',
        genres: ['Action', 'Adventure', 'Fantasy', 'Supernatural'],
        rating: 4.9,
        views: 15800000,
        bookmarks: 890000,
        synopsis: 'In a world where hunters — humans who possess magical abilities — must battle deadly monsters to protect the human race from total destruction, Sung Jinwoo, a Class E hunter, is the weakest of them all. One day, after barely surviving an overwhelmingly powerful double dungeon, a mysterious System opens up to him with the power of the "Player".',
        chapters: generateChapters(179),
        updatedAt: '2024-01-15T10:00:00Z',
        createdAt: '2018-03-25T10:00:00Z',
    },
    {
        id: '2',
        title: 'Tower of God',
        altTitles: ['신의 탑', 'Kami no Tou'],
        slug: 'tower-of-god',
        cover: 'https://placehold.co/300x450/0a0a2e/4f46e5?text=Tower+of+God&font=montserrat',
        banner: 'https://placehold.co/1200x400/0a0a2e/4f46e5?text=Tower+of+God+Banner&font=montserrat',
        type: 'manhwa',
        status: 'ongoing',
        author: 'SIU',
        artist: 'SIU',
        genres: ['Action', 'Adventure', 'Drama', 'Fantasy', 'Mystery'],
        rating: 4.7,
        views: 11200000,
        bookmarks: 670000,
        synopsis: 'What do you desire? Money and wealth? Honor and pride? Authority and power? Revenge? Or something that transcends all of them? Whatever you desire, that is here. Tower of God follows the story of Twenty-Fifth Bam as he climbs the mysterious Tower to find his friend Rachel.',
        chapters: generateChapters(550),
        updatedAt: '2024-02-20T10:00:00Z',
        createdAt: '2010-06-30T10:00:00Z',
    },
    {
        id: '3',
        title: 'The Beginning After The End',
        altTitles: ['TBATE'],
        slug: 'the-beginning-after-the-end',
        cover: 'https://placehold.co/300x450/1a0a2e/a855f7?text=TBATE&font=montserrat',
        banner: 'https://placehold.co/1200x400/1a0a2e/a855f7?text=TBATE+Banner&font=montserrat',
        type: 'manhwa',
        status: 'ongoing',
        author: 'TurtleMe',
        artist: 'Fuyuki23',
        genres: ['Action', 'Adventure', 'Fantasy', 'Isekai'],
        rating: 4.8,
        views: 9500000,
        bookmarks: 540000,
        synopsis: 'King Grey has unrivaled strength, wealth, and prestige in a world governed by martial ability. However, solitude lingers closely behind those with great power. Beneath the glamorous exterior of a powerful king lurks a shell of a man, devoid of purpose and will. Reincarnated into a new world filled with magic and monsters.',
        chapters: generateChapters(195),
        updatedAt: '2024-02-18T10:00:00Z',
        createdAt: '2018-07-07T10:00:00Z',
    },
    {
        id: '4',
        title: 'Omniscient Reader\'s Viewpoint',
        altTitles: ['전지적 독자 시점', 'ORV'],
        slug: 'omniscient-readers-viewpoint',
        cover: 'https://placehold.co/300x450/0f172a/6366f1?text=ORV&font=montserrat',
        banner: 'https://placehold.co/1200x400/0f172a/6366f1?text=ORV+Banner&font=montserrat',
        type: 'manhwa',
        status: 'ongoing',
        author: 'Sing Shong',
        artist: 'Sleepy-C',
        genres: ['Action', 'Adventure', 'Fantasy', 'Supernatural', 'Drama'],
        rating: 4.8,
        views: 8300000,
        bookmarks: 490000,
        synopsis: 'Dokja was an average office worker whose sole hobby was reading the web novel "Three Ways to Survive the Apocalypse." But when the novel suddenly becomes reality, he is the only person who knows how the world will end. Using his knowledge, he struggles to change the course of the story.',
        chapters: generateChapters(165),
        updatedAt: '2024-02-15T10:00:00Z',
        createdAt: '2020-03-11T10:00:00Z',
    },
    {
        id: '5',
        title: 'Martial Peak',
        altTitles: ['武炼巅峰'],
        slug: 'martial-peak',
        cover: 'https://placehold.co/300x450/1a0a1e/ec4899?text=Martial+Peak&font=montserrat',
        banner: 'https://placehold.co/1200x400/1a0a1e/ec4899?text=Martial+Peak+Banner&font=montserrat',
        type: 'manhua',
        status: 'ongoing',
        author: 'Momo',
        artist: 'Pikapi',
        genres: ['Action', 'Martial Arts', 'Fantasy', 'Adventure'],
        rating: 4.3,
        views: 12000000,
        bookmarks: 720000,
        synopsis: 'The journey to the martial peak is a lonely, solitary and long one. In the face of this journey, he can only rely on himself. Yang Kai, a trial disciple of the High Heaven Pavilion, was the lowest among the low.',
        chapters: generateChapters(3200),
        updatedAt: '2024-02-22T10:00:00Z',
        createdAt: '2017-06-15T10:00:00Z',
    },
    {
        id: '6',
        title: 'One Piece',
        altTitles: ['ワンピース'],
        slug: 'one-piece',
        cover: 'https://placehold.co/300x450/0a1628/eab308?text=One+Piece&font=montserrat',
        banner: 'https://placehold.co/1200x400/0a1628/eab308?text=One+Piece+Banner&font=montserrat',
        type: 'manga',
        status: 'ongoing',
        author: 'Eiichiro Oda',
        artist: 'Eiichiro Oda',
        genres: ['Action', 'Adventure', 'Comedy', 'Fantasy', 'Shounen'],
        rating: 4.9,
        views: 25000000,
        bookmarks: 1500000,
        synopsis: 'Gol D. Roger, a man known as the "Pirate King," is set to be executed. But just before his death, he confirms the existence of a great treasure, One Piece, located somewhere within the vast ocean known as the Grand Line.',
        chapters: generateChapters(1110),
        updatedAt: '2024-02-22T10:00:00Z',
        createdAt: '1997-07-22T10:00:00Z',
    },
    {
        id: '7',
        title: 'Jujutsu Kaisen',
        altTitles: ['呪術廻戦'],
        slug: 'jujutsu-kaisen',
        cover: 'https://placehold.co/300x450/1a0f2e/8b5cf6?text=Jujutsu+Kaisen&font=montserrat',
        banner: 'https://placehold.co/1200x400/1a0f2e/8b5cf6?text=JJK+Banner&font=montserrat',
        type: 'manga',
        status: 'completed',
        author: 'Gege Akutami',
        artist: 'Gege Akutami',
        genres: ['Action', 'Supernatural', 'Shounen', 'Drama'],
        rating: 4.6,
        views: 18000000,
        bookmarks: 980000,
        synopsis: 'Yuji Itadori is a boy with tremendous physical strength, though he lives a completely ordinary high school life. One day, to save a friend who has been attacked by Curses, he eats a finger of Ryomen Sukuna, taking the Curse into his own soul.',
        chapters: generateChapters(271),
        updatedAt: '2024-09-30T10:00:00Z',
        createdAt: '2018-03-05T10:00:00Z',
    },
    {
        id: '8',
        title: 'Return of the Mount Hua Sect',
        altTitles: ['화산귀환'],
        slug: 'return-of-the-mount-hua-sect',
        cover: 'https://placehold.co/300x450/0f1720/22d3ee?text=Mount+Hua&font=montserrat',
        banner: 'https://placehold.co/1200x400/0f1720/22d3ee?text=Mount+Hua+Banner&font=montserrat',
        type: 'manhwa',
        status: 'ongoing',
        author: 'Biga',
        artist: 'LICO',
        genres: ['Action', 'Martial Arts', 'Comedy', 'Adventure'],
        rating: 4.7,
        views: 7200000,
        bookmarks: 410000,
        synopsis: 'Chung Myung, the 13th disciple of the Mount Hua sect and the strongest swordsman in the world, sealed the leader of the Demonic Cult and perished. 100 years later, he is reborn as a beggar child and sets out to restore the fallen Mount Hua sect.',
        chapters: generateChapters(130),
        updatedAt: '2024-02-20T10:00:00Z',
        createdAt: '2021-07-15T10:00:00Z',
    },
    {
        id: '9',
        title: 'Demon Slayer',
        altTitles: ['鬼滅の刃', 'Kimetsu no Yaiba'],
        slug: 'demon-slayer',
        cover: 'https://placehold.co/300x450/1a0a0a/ef4444?text=Demon+Slayer&font=montserrat',
        banner: 'https://placehold.co/1200x400/1a0a0a/ef4444?text=Demon+Slayer+Banner&font=montserrat',
        type: 'manga',
        status: 'completed',
        author: 'Koyoharu Gotouge',
        artist: 'Koyoharu Gotouge',
        genres: ['Action', 'Supernatural', 'Shounen', 'Drama', 'Adventure'],
        rating: 4.7,
        views: 20000000,
        bookmarks: 1100000,
        synopsis: 'Since ancient times, rumors have abounded of man-eating demons lurking in the woods. Tanjiro Kamado discovers the truth when he finds his family slaughtered and his sister turned into a demon. He joins the Demon Slayer Corps to find a cure for Nezuko and avenge his family.',
        chapters: generateChapters(205),
        updatedAt: '2020-12-04T10:00:00Z',
        createdAt: '2016-02-15T10:00:00Z',
    },
    {
        id: '10',
        title: 'Tales of Demons and Gods',
        altTitles: ['妖神记'],
        slug: 'tales-of-demons-and-gods',
        cover: 'https://placehold.co/300x450/0a0f28/f59e0b?text=TDG&font=montserrat',
        banner: 'https://placehold.co/1200x400/0a0f28/f59e0b?text=TDG+Banner&font=montserrat',
        type: 'manhua',
        status: 'ongoing',
        author: 'Mad Snail',
        artist: 'Jiang Ruotai',
        genres: ['Action', 'Adventure', 'Fantasy', 'Martial Arts'],
        rating: 4.2,
        views: 8800000,
        bookmarks: 520000,
        synopsis: 'Nie Li, one of the strongest Demon Spiritualists, stood at the pinnacle of the martial world. However, he lost his life during the battle with the Sage Emperor and six deity ranked beasts. His soul went back in time to when he was 13 years old.',
        chapters: generateChapters(430),
        updatedAt: '2024-02-19T10:00:00Z',
        createdAt: '2015-12-08T10:00:00Z',
    },
    {
        id: '11',
        title: 'Chainsaw Man',
        altTitles: ['チェンソーマン'],
        slug: 'chainsaw-man',
        cover: 'https://placehold.co/300x450/1a0a14/f43f5e?text=Chainsaw+Man&font=montserrat',
        banner: 'https://placehold.co/1200x400/1a0a14/f43f5e?text=Chainsaw+Man+Banner&font=montserrat',
        type: 'manga',
        status: 'ongoing',
        author: 'Tatsuki Fujimoto',
        artist: 'Tatsuki Fujimoto',
        genres: ['Action', 'Supernatural', 'Horror', 'Shounen'],
        rating: 4.8,
        views: 16000000,
        bookmarks: 950000,
        synopsis: 'Denji is a teenage boy living with a Chainsaw Devil named Pochita. Due to the debt his father left behind, he has been living a rock-bottom life while repaying his debt by hunting devils. One day, Denji is killed by a devil, but Pochita merges with him.',
        chapters: generateChapters(175),
        updatedAt: '2024-02-21T10:00:00Z',
        createdAt: '2018-12-03T10:00:00Z',
    },
    {
        id: '12',
        title: 'Nano Machine',
        altTitles: ['나노머신'],
        slug: 'nano-machine',
        cover: 'https://placehold.co/300x450/0f0a2e/06b6d4?text=Nano+Machine&font=montserrat',
        banner: 'https://placehold.co/1200x400/0f0a2e/06b6d4?text=Nano+Machine+Banner&font=montserrat',
        type: 'manhwa',
        status: 'ongoing',
        author: 'Han-Joong-Wueol-Ya',
        artist: 'Geum Gang Bul Gae',
        genres: ['Action', 'Martial Arts', 'Sci-Fi', 'Fantasy'],
        rating: 4.5,
        views: 6800000,
        bookmarks: 380000,
        synopsis: 'After being implanted with a nano machine by a descendant from the future, a young boy from the Demonic Cult, Cheon Yeo-woon, begins to walk a new path. With the power of the nano machine, he starts his journey to become the strongest.',
        chapters: generateChapters(160),
        updatedAt: '2024-02-17T10:00:00Z',
        createdAt: '2020-08-20T10:00:00Z',
    },
]

export const mockReviews: Review[] = [
    {
        id: 'r1',
        userId: 'u1',
        username: 'MangaFan99',
        avatar: 'https://placehold.co/40x40/7c3aed/ffffff?text=M',
        mangaId: '1',
        rating: 5,
        content: 'Absolute masterpiece! The art, the storyline, everything is perfect. Solo Leveling redefined the manhwa genre for me.',
        createdAt: '2024-01-10T10:00:00Z',
        likes: 234,
    },
    {
        id: 'r2',
        userId: 'u2',
        username: 'WeebReader',
        avatar: 'https://placehold.co/40x40/6366f1/ffffff?text=W',
        mangaId: '1',
        rating: 5,
        content: 'The progression system is incredibly satisfying. Every power-up feels earned and the art during battle scenes is insane.',
        createdAt: '2024-01-08T10:00:00Z',
        likes: 156,
    },
    {
        id: 'r3',
        userId: 'u3',
        username: 'DarkKnight',
        avatar: 'https://placehold.co/40x40/a855f7/ffffff?text=D',
        mangaId: '1',
        rating: 4,
        content: 'Great series overall. The ending felt a bit rushed but the journey was absolutely worth it. Highly recommended!',
        createdAt: '2024-01-05T10:00:00Z',
        likes: 89,
    },
]

export const mockUser: UserProfile = {
    id: 'u1',
    username: 'MangaFan99',
    avatar: 'https://placehold.co/80x80/7c3aed/ffffff?text=MF',
    email: 'mangafan99@example.com',
    joinedAt: '2023-01-15T10:00:00Z',
    readingHistory: [
        { mangaId: '1', chapterId: 'ch-179', chapterNumber: 179, lastReadAt: '2024-02-22T10:00:00Z', progress: 100 },
        { mangaId: '2', chapterId: 'ch-420', chapterNumber: 420, lastReadAt: '2024-02-21T10:00:00Z', progress: 65 },
        { mangaId: '3', chapterId: 'ch-150', chapterNumber: 150, lastReadAt: '2024-02-20T10:00:00Z', progress: 45 },
        { mangaId: '6', chapterId: 'ch-1100', chapterNumber: 1100, lastReadAt: '2024-02-19T10:00:00Z', progress: 90 },
        { mangaId: '7', chapterId: 'ch-250', chapterNumber: 250, lastReadAt: '2024-02-18T10:00:00Z', progress: 80 },
    ],
    bookmarks: ['1', '2', '3', '4', '6', '7', '8', '11'],
    favorites: ['1', '6', '7', '11'],
}

export function formatViews(views: number): string {
    if (views >= 1000000) return `${(views / 1000000).toFixed(1)}M`
    if (views >= 1000) return `${(views / 1000).toFixed(1)}K`
    return views.toString()
}

export function formatDate(dateStr: string): string {
    const date = new Date(dateStr)
    const now = new Date()
    const diffMs = now.getTime() - date.getTime()
    const diffDays = Math.floor(diffMs / (1000 * 60 * 60 * 24))
    if (diffDays === 0) return 'Today'
    if (diffDays === 1) return 'Yesterday'
    if (diffDays < 7) return `${diffDays} days ago`
    if (diffDays < 30) return `${Math.floor(diffDays / 7)} weeks ago`
    if (diffDays < 365) return `${Math.floor(diffDays / 30)} months ago`
    return `${Math.floor(diffDays / 365)} years ago`
}

export function getMangaById(id: string): Manga | undefined {
    return mockManga.find(m => m.id === id)
}

export function getMangaBySlug(slug: string): Manga | undefined {
    return mockManga.find(m => m.slug === slug)
}
